---
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
        - name: all list user in my noed
          user: name='{{item}}' state=present
          with_items:
                   - testuser1
                   - testuser2

